name: distant_locations

on:
  push:
    paths:
      - "distant_locations/**"

env:
  PROJECT: distant_locations

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
        working-directory: ./${{ env.PROJECT }}
